### ISSUE TITLE
Why my github golang can't find in goproxy.io

### ISSUE THREAD

**Issue by nonetheless** [goproxyio/goproxy#100]
I can't find my code in https://goproxy.io/github.com/nonetheless/docker-registry-client/@v/; So when I use GOPROXY="https://goproxy.io" go get -v github.com/nonetheless/docker-registry-client; I get nothing.

**Comment by oiooj** [comment]
You have a new tag `v1.1.0`.

You should use `go get -v github.com/nonetheless/docker-registry-client@latest`
