### ISSUE TITLE
Set export GOPROXY=https://goproxy.io doesn't work .

### ISSUE THREAD

**Issue by zjylx** [goproxyio/goproxy#102]
I build my own proxy can work well.
and i want to know if the https://goproxy.io is a public proxy service?
Because `export GOPROXY=https://goproxy.io`  doesn't work for me.

**Comment by oiooj** [comment]
@zjylx Can you show me some error logs, or anything you got?

**Comment by zjylx** [comment]
I found this issue appear in the situation that can't ping goproxy.io

**Comment by oiooj** [comment]
@zjylx Thanks for your report, but Now this site is OK. You can use this tool: https://tools.ipip.net/newping.php

![image](https://user-images.githubusercontent.com/2253095/63013020-e1ecce00-bebd-11e9-90b7-d12389c0c4d7.png)

Feel free to reopen it if you have any questions.
