### ISSUE TITLE
项目中的docker文件和https://goproxy.io是什么关系

### ISSUE THREAD

**Issue by bluedragonflyliu** [goproxyio/goproxy#105]
项目中的docker文件和https://goproxy.io是什么关系 设置了环境变量后还用启动docker goproxy/goproxy吗，如果必须端口能换成别的吗还是只能用80端口

**Comment by oiooj** [comment]
@bluedragonflyliu 设置了环境变量后就直接可以用了，这个项目主要是让大家可以搭建属于自己的 goproxy.io。

**Comment by bluedragonflyliu** [comment]
谢谢
