### ISSUE TITLE
zip: not a valid zip file

### ISSUE THREAD

**Issue by jsign** [goproxyio/goproxy#107]
Using the current `latest` docker image `goproxy/goproxy`, I eventually reached the following situation in a CI pipeline with many dependencies.

Problem:
```
github.com/sirupsen/logrus@v1.4.2: zip: not a valid zip file
```

I jumped into the container to `unzip -t` the `.zip` file with result:
```
Archive:  v1.4.2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of v1.4.2.zip or
        v1.4.2.zip.zip, and cannot find v1.4.2.zip.ZIP, period.
```
I manually deleted the `.zip` file, `go get` it again with success. I saved the problematic `.zip` if may be useful.

The docker run instance wasn't using `-v` to persist the data, so I also `rm`ed the instance, run it again from zero, ran the whole CI pipeline again, unfortunately, without being able to reproduce the results. 

To be constructive, just leaving here the record that this happened to me as searching in the issues didn't produce any similar results. 

I'm not sure if the problem was saving corrupt data, or somehow the file was corrupted after saving. Maybe it may be worthwhile to verify the `.zip` file immediately after saving it, and/or while retrieving it (so if corrupted, fallback to `rm` and `go get`ing it again). Both have perf overhead, but solving this problem involves manual action (maybe activate this feature by a non-default flag). Just an idea.

**Comment by ikerlin** [comment]
we have this error too

golang: 1.13

**Comment by Momo733** [comment]
I found a similar problem about the lastest docker image goproxy/goproxy .Goproxy can't  resolve ``.`` Files or directories.
```
zip for git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999 has unexpected file git.apache.org/thrift.git@v0.12.0/.clang-format
zip for github.com/Azure/go-autorest@v11.2.7+incompatible has unexpected file github.com/Azure/go-autorest@v13.0.1+incompatible/.github/PULL_REQUEST_TEMPLATE.md
zip for github.com/DataDog/datadog-go@v0.0.0-20180822151419-281ae9f2d895 has unexpected file github.com/DataDog/datadog-go@v2.2.0+incompatible/.travis.yml
zip for github.com/cloudflare/cfssl@v0.0.0-20190510060611-9c027c93ba9e has unexpected file github.com/cloudflare/cfssl@v0.0.0-20190911221928-1a911ca1b1d6/.dockerignore
zip for github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e has unexpected file github.com/coreos/go-systemd@v0.0.0-20190719114852-fd7a80b32e1f/.travis.yml
zip for github.com/dnaeon/go-vcr@v0.0.0-20180920040454-5637cf3d8a31 has unexpected file github.com/dnaeon/go-vcr@v1.0.1/.gitignore
```
And,I found ``hub.docker.com`` image is using  different port from github Dcoekrfile.

**Comment by Momo733** [comment]
> I found a similar problem about the lastest docker image goproxy/goproxy .~~Goproxy can't resolve `.` Files or directories.~~
> 
> ```
> zip for git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999 has unexpected file git.apache.org/thrift.git@v0.12.0/.clang-format
> zip for github.com/Azure/go-autorest@v11.2.7+incompatible has unexpected file github.com/Azure/go-autorest@v13.0.1+incompatible/.github/PULL_REQUEST_TEMPLATE.md
> zip for github.com/DataDog/datadog-go@v0.0.0-20180822151419-281ae9f2d895 has unexpected file github.com/DataDog/datadog-go@v2.2.0+incompatible/.travis.yml
> zip for github.com/cloudflare/cfssl@v0.0.0-20190510060611-9c027c93ba9e has unexpected file github.com/cloudflare/cfssl@v0.0.0-20190911221928-1a911ca1b1d6/.dockerignore
> zip for github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e has unexpected file github.com/coreos/go-systemd@v0.0.0-20190719114852-fd7a80b32e1f/.travis.yml
> zip for github.com/dnaeon/go-vcr@v0.0.0-20180920040454-5637cf3d8a31 has unexpected file github.com/dnaeon/go-vcr@v1.0.1/.gitignore
> ```

Sorry,It looks like a go module problem.
