### ISSUE TITLE
Use of internal package.

### ISSUE THREAD

**Issue by tie** [goproxyio/goproxy#127]
The copy of robustio/renameio packages imports internal API, which is missing in this module.

```
github.com/goproxyio/goproxy/v2@v2.0.1/robustio/robustio_windows.go:9:2: use of internal package internal/syscall/windows not allowed
```

https://github.com/goproxyio/goproxy/blob/9a7bb4c0c90f2c4a2a5c8855ad4cea40397f0107/robustio/robustio_windows.go#L7-L15

**Comment by oiooj** [comment]
@tie You can use `pr-win-dep` branch to build, have a try.

**Comment by tie** [comment]
Thanks, now builds with `GOOS=windows`. Though there still could some cases where it’s likely to fail at runtime, e.g. `filepath.Join` calls with unix-style slash paths in `main.go` and `router.go`.

**Comment by oiooj** [comment]
@tie Now you can pull the latest code from branch `pr-win-dep`:
 I tested on a win 10:

server:
```
PS C:\> .\goproxy.exe
goproxy.io: 8.060s 200 /github.com/lodastack/agent/@v/list
goproxy.io: 1.317s 200 /github.com/lodastack/agent/@v/v0.2.2.mod
goproxy.io: 0.127s 404 /github.com/lodastack/@v/list
goproxy.io: 0.860s 404 /github.com/@v/list

```

user:
```
PS C:\Users\xxx> go get -v github.com/lodastack/agent
Fetching http://localhost:8081/github.com/lodastack/agent/@v/list
Fetching http://localhost:8081/github.com/lodastack/agent/@v/v0.2.2.mod
Fetching http://localhost:8081/github.com/lodastack/@v/list
```
