### ISSUE TITLE
sum.golang.org: go get golint ends with 410 Gone

### ISSUE THREAD

**Issue by Aazhar** [goproxyio/goproxy#129]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/build/.cache/go-build"
GOENV="/build/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/build"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build100314052=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
<pre>
go get -u  golang.org/x/lint/golint
</pre>

### What did you expect to see?

Install golint and be able to use it 

### What did you see instead?

go: finding golang.org/x/lint latest
go: downloading golang.org/x/lint v0.0.0-20191125180803-fdd1cda4f05f
verifying golang.org/x/lint@v0.0.0-20191125180803-fdd1cda4f05f: golang.org/x/lint@v0.0.0-20191125180803-fdd1cda4f05f: reading **https://goproxy.io/sumdb/sum.golang.org/lookup/golang.org/x/lint@v0.0.0-20191125180803-fdd1cda4f05f: 410 Gone**

**Comment by hulucc** [comment]
Same here.
curl https://goproxy.io/sumdb/gosum.io/lookup/github.com/digits/graphql-go@v0.0.2 => 410 Gone
curl https://gosum.io/lookup/github.com/digits/graphql-go@v0.0.2 => 200

**Comment by oiooj** [comment]
@Aazhar @hulucc Fixed online , Thanks for your report.
