### ISSUE TITLE
When install cobra I get 404 not found

### ISSUE THREAD

**Issue by triThirty** [goproxyio/goproxy#131]
When I tried to install cobra, `go get -u github.com/spf13/cobra/cobra`
I got `go get: upgrading github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e: unexpected status (https://goproxy.io/github.com/coreos/go-systemd/@v/list): 404 Not Found` message.
I had already use the master branch goproxy, but it didn't work.
My go version 1.12.7.

**Comment by oiooj** [comment]
@triThirty Please try to use `github.com/coreos/go-systemd/v22` ， because 

```
not found: module github.com/coreos/go-systemd: no matching versions for query "latest"
```
