### ISSUE TITLE
use of internal package internal/syscall/windows not allowed

### ISSUE THREAD

**Issue by gonboy** [goproxyio/goproxy#138]
**build to LinuxX64 OK.**

---

**but**
system: Win10 
go: V1.13
build version:  V2.0.1，build to Winx64 

**error:**
```bash
robustio\robustio_windows.go:9:2: use of internal package internal/syscall/windows not allowed
```

**Comment by oiooj** [comment]
@gonboy This issue already fixed by #127 ， update your codebase use `git pull origin master` and rebuilt it.

Or you could use https://github.com/goproxyio/goproxy/releases/tag/v2.0.2 release
