### ISSUE TITLE
由于企业安全需要，无法访问外网，有什么方式突破

### ISSUE THREAD

**Issue by aixiaoxiang** [goproxyio/goproxy#141]
由于企业安全需要，无法访问外网，有什么方式可以获取 goproxy.io 上面的全部镜像资源，就是相当于在企业内部部署一个 goproxy.io，并还哈有大量已经缓存的 go 开源库。比如定期同步  goproxy.io 的资源。

**Comment by oiooj** [comment]
@aixiaoxiang  无法访问外网，用什么方法定期同步呢

**Comment by aixiaoxiang** [comment]
> @aixiaoxiang 无法访问外网，用什么方法定期同步呢


有定制的虚拟桌面，通过这个可以上网，只能从虚拟桌面拷贝文件到开发机器，无法反过来。也就是开发机器本身是完全于外界隔离的

**Comment by oiooj** [comment]
@aixiaoxiang 您方便提供一下联系方式么，我私下联系您讨论下。或者直接发我邮件 admin@goproxy.io

**Comment by RainbowMango** [comment]
> 有定制的虚拟桌面，通过这个可以上网，只能从虚拟桌面拷贝文件到开发机器，无法反过来。也就是开发机器本身是完全于外界隔离的

我对这个问题感兴趣。

既然开发机跟虚拟机网络是通的，在虚拟机上布个代理不行么？
