### ISSUE TITLE
关于无法从内网Gitlab拉包的问题

### ISSUE THREAD

**Issue by eryajf** [goproxyio/goproxy#142]
在说明文档中关于从内部拉包的说明为如下启动方式：

```
./bin/goproxy -listen=0.0.0.0:80 -cacheDir=/tmp/test -proxy https://goproxy.io -exclude "git.corp.example.com,rsc.io/private"
```

从这里看起来，外部的包走 `https://goproxy.io`，内部的包走 `git.corp.example.com`，这似乎没什么问题。

但实际使用场景中，内部的包在gitlab中一般都为私有包，未经授权无法访问的，而goproxy貌似没有给出这种认证的参数，也就无法从内部拉包了。不知道是不是我的使用方式哪里有问题。

**Comment by oiooj** [comment]
@eryajf 这个是底层 git 认证的配置问题，可以把你 goproxy server 上的 key 放到内部 gitlab 的deploy key 中，可以参考这篇文章下方的评论：https://gocn.vip/topics/9831

**Comment by eryajf** [comment]
这个key已经添加，现在我可以直接 `git clone` 将对应代码下载下来，但是通过go项目去拉取的时候，finding之后，就一直卡在那里，排除网络不通，排除key的认证，不知道是否还有其他因素影响呢！

**Comment by oiooj** [comment]
@eryajf 私有库的支持你可以先试试 https://user.goproxy.io，这个功能稳定了，后面可以考虑开源出来提供给企业自己使用。

**Comment by eryajf** [comment]
感谢回复，看了配置的文档，感觉目前情况下，我这边恐怕不太方便以这种方式进行配置（公司安全方面对这种外部介入还是比较敏感的）。不知道你说的后续开源出来的形式会是怎样的一种配置，期待提供一种像现在这样配置简单，且行之有效的方案。目前我们这边内部的包可能还要走 athens 来拉取。再次感谢！
