### ISSUE TITLE
http 302 StatusCode

### ISSUE THREAD

**Issue by Dereking** [goproxyio/goproxy#145]
I run a local goproxy at my server: goproxy -proxy=https://goproxy.io .

I created a golang test project, and set $GOPROXY=mygoproxyweb, sine I run go build , I encountered a 302 redirect response from my goproxy:
Location https://goproxy.someimg.com/github.com/gin-gonic/gin/@v/v1.5.0.zip
It's very strange, I didn't find any string "someimg.com" in the goproxy code.

Is it a feature of product enviroment https://goproxy.io ?

I changed the upstream proxy to gocenter.io, It works well.
goproxy -proxy=https://gocenter.io .

Here is the curl output:
$ curl -v https://goproxy.io/github.com/gin-gonic/gin/@v/v1.5.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 119.28.201.50:443...
* TCP_NODELAY set
* Connected to goproxy.io (119.28.201.50) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
...........................(ssl)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0xe41300)
} [5 bytes data]
> GET /github.com/gin-gonic/gin/@v/v1.5.0.zip HTTP/2
> Host: goproxy.io
> user-agent: curl/7.68.0
> accept: */*
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 **302**
< server: nginx/1.16.1
< date: Thu, 12 Mar 2020 11:27:26 GMT
< content-type: text/html; charset=utf-8
< content-length: 89
< **location: https://goproxy.someimg.com/github.com/gin-gonic/gin/@v/v1.5.0.zip**
<
{ [89 bytes data]
100    89  100    89    0     0    640      0 --:--:-- --:--:-- --:--:--   644< a href="https://goproxy.someimg.com/github.com/gin-gonic/gin/@v/v1.5.0.zip">Found</a>.

* Connection #0 to host goproxy.io left intact

**Comment by oiooj** [comment]
> I created a golang test project, and set $GOPROXY=mygoproxyweb, sine I run go build , I encountered a 302 redirect response from my goproxy:
Location https://goproxy.someimg.com/github.com/gin-gonic/gin/@v/v1.5.0.zip
It's very strange, I didn't find any string "someimg.com" in the goproxy code.

> Is it a feature of product enviroment https://goproxy.io ?

Yes ,  `someimg.com` is our CDN domain, it's a new feature, we speed up developer's download all over the world via this domain. Now only zip packages will redirect to this domain.

**Comment by Dereking** [comment]
Thanks for you reply. 
Could you add an option to this project, let my local goproxy server can handle the zip rediect in server? Because I can't proxy all URL except goproxy.io.
For somebody who use goproxy in intralnet like me, please.
If the reuest is not acceptable, take it seay, I preciate your good job at this project.
