### ISSUE TITLE
使用goproxy代理后，下载的一直是旧版本的代码

### ISSUE THREAD

**Issue by readthecodes** [goproxyio/goproxy#148]
代码库地址：
https://github.com/micro/go-plugins

使用代理后无法拉最新代码，提示：https://goproxy.io/github.com/micro/go-plugins/@v/v2.0.0.info: 404 Not Found

**Comment by oiooj** [comment]
@readthecodes v2 需要使用这样的地址： `github.com/micro/go-plugins/v2`

比如下面这个： 

https://goproxy.io/github.com/micro/go-plugins/v2/@v/v2.0.0.info
