### ISSUE TITLE
go.etcd.io/etcd/clientv3 错误

### ISSUE THREAD

**Issue by must11** [goproxyio/goproxy#150]
go.etcd.io/etcd/clientv3 这个包拉取的还是旧版本的依赖，可以更新到最新的吗

**Comment by oiooj** [comment]
是的， 这个应该是个 v3 的子包，我们可以看到整个仓库的 v3 的版本列表: 

https://goproxy.io/go.etcd.io/etcd/v3/@v/list
```
v3.0.0-beta.0
v3.0.0
v3.0.1
v3.0.2
v3.0.3
v3.0.4
v3.0.5
v3.0.6
v3.0.7
v3.0.8
v3.0.9
v3.0.10
...
v3.3.20
v3.3.21
v3.3.22
v3.4.0-rc.0
v3.4.0-rc.1
v3.4.0-rc.2
v3.4.0-rc.3
v3.4.0-rc.4
v3.4.0
v3.4.1
v3.4.2
v3.4.3
v3.4.4
v3.4.5
v3.4.6
v3.4.7
v3.4.8
v3.4.9
```

但是， 这样的 go.etcd.io/etcd/clientv3 的子包却不好获取，这个情况比较复杂：
1. etcd 开发者没有在 go.etcd.io/etcd/clientv3 下声明自己的 go.mod 
2. 新建 go.etcd.io/etcd/v3 目录，将 clientv3 放置于 v3 目录下。

上面两个情况都可以解决这个问题。目前就连 google 的服务器也无法获取的：https://proxy.golang.org/go.etcd.io/etcd/clientv3/@v/list
