### ISSUE TITLE
The agent cannot meet expectations

### ISSUE THREAD

**Issue by lyb-Q** [goproxyio/goproxy#151]
> I followed the tutorial, but i didn't live up to 

![Image of Yaktocat](https://s1.ax1x.com/2020/06/24/NaDxKA.png)

```golang

go get: golang.org/x/crypto@v0.0.0-20191108234033-bd318be0434a updating to
        golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9/go.mod: verifying module: golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9/go.mod: Get "https://sum.golang.org/lookup/golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9": dial tcp 172.217.24.17:443: i/o timeout

```

**Comment by lyb-Q** [comment]
should be only ```google.golang.org/protobuf/...``` has not been downloaded,

> ```git clone https://e.coding.net/robinqiwei/googleprotobuf.git $GOPATH/src/google.golang.org/protobu```

**Comment by hxzhao527** [comment]
老哥, 你本地能直连 `google.golang.org`吗? 超时是因为网络原因, 请在国外机器部署试试.

Can you access `google.golang.org` directly? Some network problems result in *Timeout*. Try deploy proxy outside the Wall.

**Comment by oiooj** [comment]
@lyb-Q Try this:
```
export GOPROXY="http://127.0.0.1:8888" && go get -x golang.org/x/crypto
```

**Comment by lyb-Q** [comment]
@hxzhao527 @oiooj 使用代理只有```google.golang.org/protobuf/...```这个包没有下载下来，我不清楚是什么原因，
我用其他方式替代了
```git clone https://e.coding.net/robinqiwei/googleprotobuf.git $GOPATH/src/google.golang.org/protobuf/...```


Using the agent only ''google.golang.org/protobuf/...' this package has not been downloaded down, I don't know why,
I've replaced it in some other way.
```git clone https://e.coding.net/robinqiwei/googleprotobuf.git $GOPATH/src/google.golang.org/protobuf/...```

**Comment by oiooj** [comment]
@lyb-Q I also met the same problem, because "google" in the URL, so we can not access this data, please use HTTPS, and this issue will be fixed.
