### ISSUE TITLE
The zip file is a text file when the HTTP response code is 302

### ISSUE THREAD

**Issue by mumuhhh** [goproxyio/goproxy#155]
for example

**Comment by mumuhhh** [comment]
github.com/go-sql-driver/mysql/@v/v1.5.0.zip 

<a href="https://goproxy.onetool.net/github.com/go-sql-driver/mysql/@v/v1.5.0.zip">Found</a>.

**Comment by mumuhhh** [comment]
github.com/go-sql-driver/mysql/@v/v1.5.0.zip

> <a href="https://goproxy.onetool.net/github.com/go-sql-driver/mysql/@v/v1.5.0.zip">Found</a>.

**Comment by hxzhao527** [comment]
what is cmd? `go get github.com/go-sql-driver/mysql`?

or you access the zip file directly?

**Comment by mumuhhh** [comment]
`https://goproxy.io/github.com/go-sql-driver/mysql/@v/v1.5.0.zip` redirection to `https://goproxy.onetool.net/github.com/go-sql-driver/mysql/@v/v1.5.0.zip` causes the cache zip content to be `<a href="https://goproxy.onetool.net/github.com/go-sql-driver/mysql/@v/v1.5.0.zip">Found</a>.`. The zip file is a text file

**Comment by mumuhhh** [comment]
It's caused by site redirection，goproxy service download cache file is an invalid zip file

**Comment by hxzhao527** [comment]
<img width="473" alt="图片" src="https://user-images.githubusercontent.com/8402502/91676464-75994700-eb72-11ea-9855-aeaf6dcb5c48.png">

<img width="382" alt="图片" src="https://user-images.githubusercontent.com/8402502/91676483-877aea00-eb72-11ea-9356-a36df008825f.png">

**Comment by mumuhhh** [comment]
sorry
I'm talking about files cached by the goproxy service

**Comment by mumuhhh** [comment]
![1598840320(1)](https://user-images.githubusercontent.com/14306508/91676745-6961b980-eb73-11ea-89c9-c1d3825e0fac.png)
The cache file is invalid zip, when proxy use `https://goproxy.io/`

**Comment by oiooj** [comment]
@mumuhhh Yes, maybe this is a bug introduced by #153, thanks.

**Comment by oiooj** [comment]
@mumuhhh We fixed this issue at master branch, please pull the latest code and rebuild it. we should add more tests for this.
Thanks again.
