### ISSUE TITLE
go get picks incorrect version

### ISSUE THREAD

**Issue by aletheia7** [goproxyio/goproxy#159]
Running ```go get github.com/goproxyio/goproxy``` parses the wrong version number and produces the following error:
```
$ go get  github.com/goproxyio/goproxy
go: finding module for package github.com/goproxyio/goproxy/internal/modload
go: finding module for package github.com/goproxyio/goproxy/internal/cfg
go: finding module for package github.com/goproxyio/goproxy/internal/modfetch
go: finding module for package github.com/goproxyio/goproxy/internal/module
go: finding module for package github.com/goproxyio/goproxy/internal/modfetch/codehost
go: finding module for package github.com/goproxyio/goproxy/internal/cfg
go: finding module for package github.com/goproxyio/goproxy/internal/modfetch
go: finding module for package github.com/goproxyio/goproxy/internal/module
go: finding module for package github.com/goproxyio/goproxy/internal/modfetch/codehost
go: finding module for package github.com/goproxyio/goproxy/internal/modload
../../go/pkg/mod/github.com/goproxyio/goproxy@v1.0.0/pkg/proxy/proxy.go:12:2: module github.com/goproxyio/goproxy@latest found (v1.0.0), but does not contain package github.com/goproxyio/goproxy/internal/cfg
../../go/pkg/mod/github.com/goproxyio/goproxy@v1.0.0/pkg/proxy/proxy.go:13:2: module github.com/goproxyio/goproxy@latest found (v1.0.0), but does not contain package github.com/goproxyio/goproxy/internal/modfetch
../../go/pkg/mod/github.com/goproxyio/goproxy@v1.0.0/pkg/proxy/proxy.go:14:2: module github.com/goproxyio/goproxy@latest found (v1.0.0), but does not contain package github.com/goproxyio/goproxy/internal/modfetch/codehost
../../go/pkg/mod/github.com/goproxyio/goproxy@v1.0.0/pkg/proxy/proxy.go:15:2: module github.com/goproxyio/goproxy@latest found (v1.0.0), but does not contain package github.com/goproxyio/goproxy/internal/modload
../../go/pkg/mod/github.com/goproxyio/goproxy@v1.0.0/pkg/proxy/proxy.go:16:2: module github.com/goproxyio/goproxy@latest found (v1.0.0), but does not contain package github.com/goproxyio/goproxy/internal/module
```
For some reason go get thinks the latest version is v1.0.0.

Running ```go get  github.com/goproxyio/goproxy@master``` produces the following error:
```
go get github.com/goproxyio/goproxy@master: github.com/goproxyio/goproxy@v1.0.1-0.20200831065954-a4e417a2ce95: invalid version: go.mod has post-v1 module path "github.com/goproxyio/goproxy/v2" at revision a4e417a2ce95

```

go version: 1.15.2

**Comment by oiooj** [comment]
@aletheia7 Please use:

```
go get github.com/goproxyio/goproxy/v2
```

This declared in `go.mod` file.

**Comment by aletheia7** [comment]
> Executing the following commands:
> 
> ```
> $ go list -versions -m github.com/goproxyio/goproxy
> github.com/goproxyio/goproxy v1.0.0
> 
> $ go list -versions -m github.com/goproxyio/goproxy/v2
> github.com/goproxyio/goproxy/v2 v2.0.0-beta v2.0.0 v2.0.1 v2.0.2 v2.0.3 v2.0.4 v2.0.5
> ```
> 
> I would have expected the first command to show all of the versions v1.0.0 - v2.0.5.
> 
> I get all of the versions with go-sqlite3:
> 
> ```
> $ go list -versions -m github.com/mattn/go-sqlite3
> go: downloading github.com/mattn/go-sqlite3 v1.14.4
> github.com/mattn/go-sqlite3 v1.0.0 v1.1.0 v1.2.0 v1.3.0 v1.4.0 v1.5.0 v1.6.0 v1.7.0 v1.8.0 v1.9.0 v1.10.0 
> v1.11.0 v1.12.0 v1.13.0 v1.14.0 v1.14.1 v1.14.2 v1.14.3 v1.14.4 v2.0.0+incompatible v2.0.1+incompatible 
> v2.0.2+incompatible v2.0.3+incompatible
> ```
> 
> I think if you remove the "/v2" in your go.mod file it would give you all of the versions.

Disregards. https://blog.golang.org/v2-go-modules requires adding the /v2.

**Comment by aletheia7** [comment]
go list -versions cannot find v2+ by default. This is not an issue with goproxy.
