### ISSUE TITLE
How to perform health check?

### ISSUE THREAD

**Issue by donovanrost** [goproxyio/goproxy#189]
I'm hosting this on AWS Fargate. Fargate requires a health check. Using "/" as the route to perform a health check doesn't return 200 or 404, which would be valid responses. 

Is there a recommend  end point to use for performing a health check?

**Comment by igorpupkinable** [comment]
@donovanrost I know it been a while but since you have closed the ticket... Can remember how you solved it at the end?
Sorry for necroposting.

**Comment by donovanrost** [comment]
No, I have literally no memory of opening this ticket
