### ISSUE TITLE
failed to download pdfcpu  when use proxy.golang.com.cn

### ISSUE THREAD

**Issue by hawayiii** [goproxyio/goproxy#200]
when use GORPOXY=proxy.golang.com.cn, 
then  GET https://proxy.golang.com.cn/github.com/pdfcpu/pdfcpu/@v/v0.3.11.zip return EOF

please help check this error

**Comment by oiooj** [comment]
I'm investigating this issue. Thanks for your report.

**Comment by oiooj** [comment]
This issue fixed online, please confirm @hawayiii @MDUK0001

**Comment by hawayiii** [comment]
thx.
can shard what reason cause this issue ?

**Comment by oiooj** [comment]
The CDN provider request our source site has some problem, some requests reset by the peer，now fixed.
