### ISSUE TITLE
gosum.io responds with 'Not found' for most queries

### ISSUE THREAD

**Issue by aegistudio** [goproxyio/goproxy#202]
Have a try:

```
$ env GOPROXY=https://goproxy.io GOSUMDB=gosum.io+ce6e7565+AY5qEHUk/qmHc5btzW45JVoENfazw8LielDsaI+lEbq6 go get github.com/goproxyio/goproxy@v1.0.0
go: downloading github.com/goproxyio/goproxy v1.0.0
go get github.com/goproxyio/goproxy@v1.0.0: github.com/goproxyio/goproxy@v1.0.0: verifying module: github.com/goproxyio/goproxy@v1.0.0: reading https://gosum.io/lookup/github.com/goproxyio/goproxy@v1.0.0: 404 Not Found
        server response: Not Found
```

Very likely to be a temporary failure.

**Comment by hxzhao527** [comment]
There seem an infinite loop here  when `enableGoogleSumDB==false`

https://github.com/goproxyio/goproxy/blob/e03dc0f0bf84ec8ea486c6976e966dc3038772d3/sumdb/handler.go#L47-L48

https://github.com/goproxyio/goproxy/blob/e03dc0f0bf84ec8ea486c6976e966dc3038772d3/sumdb/handler.go#L56-L59

**Comment by hxzhao527** [comment]
@aegistudio  
I guess that because *gosum.io* have its own storage,  `goproxy@v1.0.0` is too old that `gosum.io` don't have its checksum.

but the official sumdb has `curl https://sum.golang.google.cn/lookup/github.com/goproxyio/goproxy@v1.0.0`.

**Comment by aegistudio** [comment]
> @aegistudio I guess that because _gosum.io_ have its own storage, `goproxy@v1.0.0` is too old that _gosum.io_ don't have its checksum.
> 
> but the official sumdb has `curl https://sum.golang.google.cn/lookup/github.com/goproxyio/goproxy@v1.0.0`

Great, I'll have a try.

**Comment by oiooj** [comment]
Gosum.io Server go offline in last week, the service is now back, sorry about that.
