### ISSUE TITLE
gosum.io responds with 'Not found' for package `gopkg.in/ini.v1`

### ISSUE THREAD

**Issue by zzjin** [goproxyio/goproxy#205]
RT

 `curl https://goproxy.io/sumdb/gosum.io/lookup/gopkg.in/ini.v1@v1.66.6` or `curl https://proxy.golang.com.cn/sumdb/gosum.io/lookup/gopkg.in/ini.v1@v1.66.6` return `not found`

But `curl https://sum.golang.google.cn/lookup/gopkg.in/ini.v1@v1.66.6` return fine.

Maybe #202 not fully fixed. `gosum.io` is not synced with upstream?

**Comment by oiooj** [comment]
The ca certs expired on the server, updated. Thanks @zzjin
