### ISSUE TITLE
How do I know which open source protocol is used for open source components?

### ISSUE THREAD

**Issue by Oliver-Wu** [goproxyio/goproxy#206]
Hello, how do I know which open source protocol is used for open source components? If any label on the component?

**Comment by hxzhao527** [comment]
1. goproxy.io does't manage the license. You need check it by yourself.
2. the go toolchain does't care about the license either. 
3. even private, `go get` could also fetch if you have access of the repo.

ref: 
* [Go Modules Reference](https://go.dev/ref/mod)

**Comment by Oliver-Wu** [comment]
Thanks
