### ISSUE TITLE
gosum.io source code

### ISSUE THREAD

**Issue by futurist** [goproxyio/goproxy#213]
There's a Download link in https://gosum.io/ page, but cannot found the source code in this repo, is it open sourced? where can find it?

Thank you!

**Comment by oiooj** [comment]
Hey, this project is not yet open source, but this project based on https://github.com/golang/mod/blob/master/sumdb/server.go，based on this code, you can easy implement a sumdb server.

**Comment by futurist** [comment]
OK, thank you for the info.
