### ISSUE TITLE
goproxy.io/sumdb proxy is not correct

### ISSUE THREAD

**Issue by Jy-poi** [goproxyio/goproxy#215]
![image](https://user-images.githubusercontent.com/28185177/220522338-732bf9c9-9b6c-45d8-8f22-86bdffb91ce7.png)
reproduce method:
```bash
go clean -modcache
export GOPROXY=https://goproxy.io,direct
go mod download github.com/Masterminds/sprig@v2.22.0+incompatible
```
use GOPROXY=direct，it works.
also found: https://goproxy.io/sumdb/sum.golang.org/tile/8/1/237 and https://sum.golang.org/tile/8/1/237 return is different.

Is goproxy.io getting something wrong?

**Comment by hxzhao527** [comment]
may same with #209

**Comment by Jy-poi** [comment]
Today [https://goproxy.io](https://goproxy.io) acts normal，I can go mod download this package now.

**Comment by Jy-poi** [comment]
Close this issue.
