### ISSUE TITLE
Checksum verification behaviour mismatch with other proxies

### ISSUE THREAD

**Issue by silverwind** [goproxyio/goproxy#216]
A recurring issues with this proxy is that when using it, checksums verification differs from other proxies when the module's  source repo re-tags the same version again. For example:

```bash
go clean -modcache && GOPROXY="https://proxy.golang.org" go install github.com/swaggo/swag/cmd/swag@v1.6.6
go clean -modcache && GOPROXY="https://goproxy.cn" go install github.com/swaggo/swag/cmd/swag@v1.6.6
go clean -modcache && GOPROXY="https://goproxy.io" go install github.com/swaggo/swag/cmd/swag@v1.6.6
```

First two commands works, the last one fails with mismatch:

```
go: github.com/swaggo/swag/cmd/swag@v1.6.6: github.com/swaggo/swag@v1.6.6: verifying module: checksum mismatch
  downloaded: h1:ujSziE+CfBxr5eIsVJgjGNbDxq1zPfLHxlu5NJmRFSQ=
  sum.golang.org: h1:3YX5hmuUyCMT/OqqnjW92gULAfHg3hVjpcPm53N64RY=
```

Verifying the checksums shows that `gosum.io` has recorded the same hash that was downloaded while `sum.golang.org`  contains the old invalid hash:

```bash
curl -s https://sum.golang.org/lookup/github.com/swaggo/swag@v1.6.6 | grep '1.6.6 '
# github.com/swaggo/swag v1.6.6 h1:3YX5hmuUyCMT/OqqnjW92gULAfHg3hVjpcPm53N64RY=
curl -s https://gosum.io/lookup/github.com/swaggo/swag@v1.6.6 | grep '1.6.6 '
# github.com/swaggo/swag v1.6.6 h1:ujSziE+CfBxr5eIsVJgjGNbDxq1zPfLHxlu5NJmRFSQ=
```

I think the only reason why the other proxies work is that they have the ability to accept multiple hashes for the same module identifier. Am I seeing this correctly?

**Comment by oiooj** [comment]
Hi @silverwind `sumdb` service is a append only service, the checksum of a module will be recored when the sumdb service  first meet the module, but some repo authors may change the tag (retag). 

The first two proxies always keep. (cached) the old zip module package, so the checksum is same with sum.golang.org.
but goproxy.io cached the latest module package.

**Comment by silverwind** [comment]
I'm using the athens proxy now and there, I have been able to solve the issue by having the proxy download via the official proxy, e.g. a chain of two proxies:

https://github.com/gomods/athens/issues/1696#issuecomment-803276359

I think this is a common enough error that you may want to consider having an option for this as well on this proxy.
