### ISSUE TITLE
Get "xxx.info" EOF

### ISSUE THREAD

**Issue by biubiudu** [goproxyio/goproxy#218]
A private goproxy is set up within the company. When the following command is executed 
``` shell
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
```
**It sometimes succeeds and sometimes fails**, and the error message of failure is 
```
2023-06-26 19:33:56.485280 | devops-centos7-go | go: downloading github.com/golangci/golangci-lint v1.47.3
2023-06-26 19:34:46.473464 | devops-centos7-go | go: github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3: github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3: Get "http://goproxy.easystack.io/github.com/golangci/golangci-lint/cmd/golangci-lint/@v/v1.47.3.info": EOF
```
check the background log information is like this 

```
goproxy.io: ------ --- /github.com/@v/v1.47.3.info [proxy]
goproxy.io: ------ --- /github.com/golangci/golangci-lint/cmd/golangci-lint/@v/v1.47.3.info [proxy]
goproxy.io: ------ --- /github.com/golangci/golangci-lint/@v/v1.47.3.info [cached]
goproxy.io: 0.000s 200 /github.com/golangci/golangci-lint/@v/v1.47.3.info
goproxy.io: 10.604s 200 /sumdb/sum.golang.org/lookup/github.com/golangci/golangci-lint@v1.47.3
goproxy.io: 0.218s 200 /sumdb/sum.golang.org/tile/8/1/136
goproxy.io: 0.225s 200 /sumdb/sum.golang.org/tile/8/0/x070/359.p/104
goproxy.io: http: proxy error: context canceled
goproxy.io: 50.000s 502 /github.com/@v/v1.47.3.info
goproxy.io: http: proxy error: context canceled
goproxy.io: 50.000s 502 /github.com/golangci/golangci-lint/cmd/golangci-lint/@v/v1.47.3.info
```
What is the reason and how to solve it？

**Comment by biubiudu** [comment]
实际情况是goproxy server已经把golangci-lint包及依赖都缓存了下来，按常理来说是不应该出问题。所以有没有可能是做sum校验的时候出的错呢？

**Comment by oiooj** [comment]
Please log your command that how to start the service?

**Comment by biubiudu** [comment]
> Please log your command that how to start the service?

```
./goproxy -listen=0.0.0.0:8080 -cacheDir= /go-cache -proxy=https://goproxy.io -exclude=review.xxx.cn
```
Is it possible the error is caused by the network failure to goproxy.io ?

**Comment by oiooj** [comment]
Emmm, `goproxy.io` using Cloudflare, but this service is not stable if you are in China mainland.

**Comment by biubiudu** [comment]
> Emmm, `goproxy.io` using Cloudflare, but this service is not stable if you are in China mainland.

当我把启动参数中的`https://goproxy.io`换成`https://goproxy.cn`后，执行 go install的时候又会出现必现的报错
```
2023-07-04 10:02:36.896504 | devops-centos7-go | go: github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3: github.com/golangci/golangci-lint@v1.47.3: verifying module: github.com/golangci/golangci-lint@v1.47.3: reading http://goproxy.myproxy.io/sumdb/sum.golang.org/lookup/github.com/golangci/golangci-lint@v1.47.3: 410 Gone
2023-07-04 10:02:36.896711 | devops-centos7-go |  server response: Get "https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/golangci/golangci-lint@v1.47.3": dial tcp 104.26.4.191:443: i/o timeout
```
GOSUMDB是也需要对应的配置上吗？

**Comment by hxzhao527** [comment]
> server response: Get "https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/golangci/golangci-lint@v1.47.3": dial tcp 104.26.4.191:443: i/o timeout

**Comment by biubiudu** [comment]
> 网不通吗? 能打开`https://goproxy.io`吗
昨天在goproxy的服务容器里 ping `goproxy.io`不通，我本地也ping不通，这个server是不是出问题了。

另外我把服务启动时的`-proxy`的设置成了`proxy.golang.com.cn`，然后拉取包就基本正常了。

但我不太理解的是 用`goproxy.cn`为啥就会出现下面这个问题，查看服务日志也会出现了302的返回码。
```
........invalid response from proxy "http://goproxy.xxxxxxx.io": invalid character 'o' in literal null (expecting 'u')
```

**Comment by longfei-zhang** [comment]
goproxy 本地和服务器ping不通的时候，本地打开全局翻墙代理就可以ping通，网页也可以打开。
目前的解决方案还是需要配置国内可以稳定访问的地址。
如果国内没有可使用的稳定的地址，我们可以在服务器端安装open vpn

`nslookup goproxy.io
Server:                114.114.114.114
Address:        114.114.114.114#53

Non-authoritative answer:
Name:        goproxy.io
Address: 104.26.5.191
Name:        goproxy.io
Address: 104.26.4.191
Name:        goproxy.io
Address: 172.67.69.138`

将goproxy.io 返回的address添加路由配置走vpn代理, 例如
`ip r add 172.67.69.138 via 10.6.0.1`
