### ISSUE TITLE
建议修改一下首页https://goproxy.io/的使用示例

### ISSUE THREAD

**Issue by hailaz** [goproxyio/goproxy#220]
参考https://goproxy.cn/
```shell
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.io,direct
```

**Comment by httpcheck** [comment]
不如直接提pr

**Comment by oiooj** [comment]
@hailaz 谢谢您的反馈，但是目前 Google 在维护的版本中已经无需设置 `GO111MODULE=on` 了，另外 `go env -w` 也有一些弊端，受历史演进影响，如果用户之前配置了环境变量，使用 `go env -w` 是不生效的。
