### ISSUE TITLE
无法安装golang.org/x/net

### ISSUE THREAD

**Issue by lcg635** [goproxyio/goproxy#24]
1. 在google cloud的一台机器上安装了自己编译出来的goproxy
2. 本地mac笔记本设置了GOPROXY
3. go get -v -u golang.org/x/net
本地日志:
go: finding golang.org/x/net latest
go: finding golang.org/x latest
go: finding golang.org latest
go get golang.org/x/net: no matching versions for query "latest"

goproxy日志:
2018/12/26 14:11:39 goproxy: 119.130.228.90:30467 download /golang.org/x/net/@v/list
2018/12/26 14:11:39 goproxy: 119.130.228.90:30467 download /golang.org/x/net/@latest
2018/12/26 14:11:39 download get err not in cache
2018/12/26 14:11:40 goproxy: 119.130.228.90:30467 download /golang.org/x/@v/list
2018/12/26 14:11:40 goproxy: 119.130.228.90:30467 download /golang.org/x/@latest
2018/12/26 14:11:40 lookup failed: unrecognized import path "golang.org/x" (parse https://golang.org/x?go-get=1: no go-import meta tags ())
2018/12/26 14:11:40 goproxy: unrecognized import path "golang.org/x" (parse https://golang.org/x?go-get=1: no go-import meta tags ())
2018/12/26 14:11:40 goproxy: 119.130.228.90:30467 download /golang.org/@v/list
2018/12/26 14:11:40 goproxy: 119.130.228.90:30467 download /golang.org/@latest
2018/12/26 14:11:40 lookup failed: unrecognized import path "golang.org" (parse https://golang.org?go-get=1: no go-import meta tags ())
2018/12/26 14:11:40 goproxy: unrecognized import path "golang.org" (parse https://golang.org?go-get=1: no go-import meta tags ())

但是如果指定了版本号: 
go get -v -u golang.org/x/net@v0.0.0-20181220203305-927f97764cc3
就可以安装成功

**Comment by oiooj** [comment]
Yes，I have the same issue，you can use https://github.com/oiooj/goproxy/tree/pr-fix-latest, I fixed this issue at that branch, but it dep on `go` command. I will fix this problem at master ASAP, Thank you.

**Comment by oiooj** [comment]
cc @hxzhao527

**Comment by lcg635** [comment]
@oiooj 
Thanks very much.

**Comment by hxzhao527** [comment]
assign to me. I will handle this.

**Comment by hxzhao527** [comment]
committed
