### ISSUE TITLE
can't get cloud.google.com/go

### ISSUE THREAD

**Issue by lcg635** [goproxyio/goproxy#32]
error: 
``` 
read: connection reset by peer
```

goproxy log:
```
2018/12/28 00:08:24 goproxy: 183.6.55.60:52545 request /cloud.google.com/go/
2018/12/28 00:08:24 goproxy: 183.6.55.60:52627 request /cloud.google.com/go/
2018/12/28 00:08:24 goproxy: 183.6.55.60:52628 request /cloud.google.com/go/

**Comment by hxzhao527** [comment]
1. How do you get this package? `go get` ? `go mod`? Can you provide your command?
2. where is goproxy deployed? inside wall? outside?

**Comment by oiooj** [comment]
@lcg635  Of course you can't fetch `cloud.google.com/go`, you need to cross the `wall`.

**Comment by hxzhao527** [comment]
`curl -v http://xxxxxx/cloud.google.com/go/@v/list` and what you get?

**Comment by lcg635** [comment]
@hxzhao527 I can't get this url. I will try deploy goproxy in Hong Kong later, thank you !

**Comment by hxzhao527** [comment]
@lcg635 any progress?

**Comment by oiooj** [comment]
Fixed

**Comment by bobower** [comment]
> @hxzhao527 I can't get this url. I will try deploy goproxy in Hong Kong later, thank you !

Hi, Have you deployed the goproxy program in Hong Kong?Has the reset problem been solved?
