### ISSUE TITLE
Add more tests into proxy_test

### ISSUE THREAD

**Issue by oiooj** [goproxyio/goproxy#38]
We need to add more tests into `proxy_test.go`, like:

- [x] golang.org/x/net  latest (pass)
- [x] github.com/micro/go-api/resolver  cbf6e7fcfe8a (maybe fail)
- [x] github.com/micro/go-api  master (pass)
- [x] cloud.google.com/go   (pass)
- [x] github.com/oiooj/agent  v0.2.2  (maybe fail)
- [x] github.com/mritd/sshutils  v0.0.0-20181227030943-b85e20a7d4b8 (pass)

**Comment by hxzhao527** [comment]
You mean support `go get` no matter what `GO111MODULE ` is?

**Comment by hxzhao527** [comment]
Plan: add docker image test before 除夕.

**Comment by oiooj** [comment]
We fixed `github.com/micro/go-api master` today, thanks @hxzhao527.

**Comment by oiooj** [comment]
All fixed, thanks @hxzhao527
