### ISSUE TITLE
Discussion: to support private repo?

### ISSUE THREAD

**Issue by hxzhao527** [goproxyio/goproxy#41]
same with title.

Maybe we can abstract https://github.com/goproxyio/goproxy/blob/26d189ed77e88a022b421e80e60814214b9301f3/pkg/proxy/proxy.go#L135 to make it support private repo, such as attach basic-auth and so on.

**Comment by hxzhao527** [comment]
I think the way `grpc compile plugin` use is pretty.

**Comment by prologic** [comment]
Who is working on this? Looks like [athens](https://github.com/gomods/athens) has support for Private Repositories; but I haven't tried it yet. Can we learn from their implementation?

**Comment by hxzhao527** [comment]
@prologic This just a proposal now. Maybe after 春节(a chinese festival) and I find a new company, I will start this work, and submit a demo implement.

I noticed athens too. But it seems that we have a big different basement from it. I will study about it deeply this week, and sync if I have any progress.

If you have any idea about implement, just post.Thanks a lot.

**Comment by prologic** [comment]
Any further updates on this? Any work-in-progress?

**Comment by hxzhao527** [comment]
I'm busy with finding a job, so not in process.

**Comment by Zereker** [comment]
这个需求还是很迫切的

**Comment by SatanDaddy** [comment]
urgent need~

**Comment by prologic** [comment]
Any updates on this feature request? Anyone working on it?

**Comment by kuange** [comment]
持续关注!

**Comment by prologic** [comment]
> 持续关注!

Translation?

**Comment by kuange** [comment]
> > 持续关注!
> 
> Translation?

keep watching...

**Comment by kuange** [comment]
@prologic 
keep watching...

**Comment by prologic** [comment]
Thanks :)

**Comment by oiooj** [comment]
If your Go version >= 1.13, the `GOPRIVATE` environment variable controls which modules the go command considers to be private (not available publicly) and should therefore not use the proxy or checksum database. For example:

```
go env -w GOPROXY=https://goproxy.io,direct
# Set environment variable allow bypassing the proxy for selected modules
go env -w GOPRIVATE=*.corp.example.com
```
And I believe this is more security.

**Comment by daqingshu** [comment]
athens support

**Comment by imneov** [comment]
Maybe we can use router mode to support private repo.

```
                                         direct
                      +----------------------------------> private repo
                      |
                 match|pattern
                      |
                  +---+---+           +----------+
go get  +-------> |goproxy| +-------> |goproxy.io| +---> golang.org/x/net
                  +-------+           +----------+
                 router mode           proxy mode
```

PR https://github.com/goproxyio/goproxy/pull/88

**Comment by psy-core** [comment]
@imneov  how to configure username and password for private repo if i use router mode?

**Comment by Momo733** [comment]
> If your Go version >= 1.13, the `GOPRIVATE` environment variable controls which modules the go command considers to be private (not available publicly) and should therefore not use the proxy or checksum database. For example:
> 
> ```
> go env -w GOPROXY=https://goproxy.io,direct
> # Set environment variable allow bypassing the proxy for selected modules
> go env -w GOPRIVATE=*.corp.example.com
> ```
> 
> And I believe this is more security.

My Go version is  go1.13rc2 linux/amd64, set go env as you like,and use router mode to exclude my private repo,but goproxy doesn't work.

```
[root@node2 ~]# ./goproxy -listen=0.0.0.0:8081 -cacheDir=/tmp/test -proxy https://goproxy.io -exclude "gitlab.private.com/private/private-base"
goproxy.io: ProxyHost https://goproxy.io
goproxy.io: ExcludeHost gitlab.private.com/private/private-base
goproxy.io: ------ --- /gitlab.private.com/private/private-base/@v/list [direct]
goproxy.io: 0.009s 404 /gitlab.private.com/private/private-base/@v/list
```
thx again.

**Comment by oiooj** [comment]
@Momo733 Your seeting `-exclude "gitlab.private.com/private/private-base"` works. 

But your git server return 404.  It seems that you don't have permission to fetch `gitlab.private.com/private/private-base` on `node2`.

**Comment by Momo733** [comment]
@hxzhao527 @oiooj  Thx,I think the reason is my private repo which isn't used TLS.

And I used another  solution by setting  GOPRIVATE env to exclude my private repo,goproxy is only for public packages.I think it's a good solution for me.What I need to wait for is Go1.13 released.

I hope my experience will be helpful to this discussion.

**Comment by oiooj** [comment]
Go 1.13 released.

**Comment by eryajf** [comment]
> setting GOPRIVATE env to exclude my private repo

这应该并不是一个完美的解决方案吧，这样设置之后，所有编译场景中，需要拉取gitlab内部包的时候，都需要经过认证之后才行，不算优雅。我们还是应该回归到将从内部gitlab拉包的任务交给proxy来完成才合适吧，这样只需要proxy对gitlab的项目有认证就可以了。

**Comment by oiooj** [comment]
@eryajf This feature is already done, you can try https://user.goproxy.io and the doc: https://goproxy.io/docs/goproxyio-private.html

Feel free to open an issue if you meet any bug.
