### ISSUE TITLE
Docker image is broken

### ISSUE THREAD

**Issue by prologic** [goproxyio/goproxy#42]
Because you are not building a static binary in the build image and use the `golang:1.11` tag which uses an Ubuntu/Debian based file systme you are building against glibc. In the runtime image you then copy the resulting binary but use the `alpine` base image.

This doesn't work :/

```#!bash
$ dki -t --rm goproxy/goproxy /bin/sh
/ # goproxy
/bin/sh: goproxy: not found
/ # ldd /bin/goproxy
	/lib64/ld-linux-x86-64.so.2 (0x7ffba950e000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7ffba950e000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ffba950e000)
```

Either we need to:

* Build a static binary in the build iamge

or

* Use the same base image root file-system so expected run-time libraries are the same.

I can submit a PR to fix this -- I'll likely do the later and use `golang:alpine` for the builder image.

**Comment by hxzhao527** [comment]
Yes.There is a error in dockerfile, which caused by me.  I'm sorry. 

 To change the builder image, maybe not the best way. This is not the main problem.
As you see by `ldd`, it depends on `ld-linux-x86-64.so` which is 64bits.

I have tried to change the builder image. This needs to change other file, like `generate.sh`.

So change `go build` to `GOARCH=386 GOOS=linux go build` will work.

Welcome to submit a PR. Thanks a lot.

**Comment by prologic** [comment]
Btw... Why are we pulling in internal code from Go -- `cmd/internal/...` into this project in the first place? This seems to get run by `go generate` and `build/generate.sh` :/ This seems really weird to me that we're relying on internal APIs and copying them in-place.

**Comment by hxzhao527** [comment]
> Btw... Why are we pulling in internal code from Go -- `cmd/internal/...` into this project in the first place? This seems to get run by `go generate` and `build/generate.sh` :/ This seems really weird to me that we're relying on internal APIs and copying them in-place.

Haha. This may belongs  #41 .I will talk about this in there.

**Comment by lovejoy** [comment]
how long the image will update ?

**Comment by hxzhao527** [comment]
> how long the image will update ?

Ready now.

**Comment by prologic** [comment]
`By goproxy • Updated 7 minutes ago`

It's already updated

See: https://hub.docker.com/r/goproxy/goproxy
