### ISSUE TITLE
Docker Hub -> Automated Build

### ISSUE THREAD

**Issue by prologic** [goproxyio/goproxy#44]
Before we merge #43 -- Can you please remove the Docker Hub repo https://hub.docker.com/r/goproxy/goproxy and re-create it as an "Automated Build" so it builds automatically on new pushes to the Github repo?

This makes deployments far easier and more convenient as I can be sure that `latest` points to `mazter` and tags points to released versions.

**Comment by oiooj** [comment]
`AUTOTEST` enabled, we want to provide a stable image version for users.

**Comment by prologic** [comment]
> `AUTOTEST` enabled, we want to provide a stable image version for users.

Sorry I'm not sure what this comment means?

I an ideal world; `master` and therefore the `latest` tagged Docker Hub image //should// always be stable right? (//provided of course there is a decent unit test suite and PRs that break the test suite are blocked//) Or am I missing something?
