### ISSUE TITLE
unknown version

### ISSUE THREAD

**Issue by zedisdog** [goproxyio/goproxy#54]
Hi,I use `go mod download`,I got this:
![2](https://user-images.githubusercontent.com/8280666/53418874-b3645f00-3a13-11e9-9ac9-c2f5858f68aa.png)
then I accessed `https://goproxy.io/github.com/micro/go-micro/@v/v0.27.0.info` by chrome, and it was blank. 
v0.27.0 is the newest version of go-micro.
so does the `goproxy.io` need some time for synchronization？

**Comment by oiooj** [comment]
Fixed now, but I'm also confused with this issue.

`https://goproxy.io/github.com/micro/go-micro/@v/list`

**Comment by zedisdog** [comment]
hi, thanks very much! this project helps me a lot :)
