### ISSUE TITLE
build failed in go1.12

### ISSUE THREAD

**Issue by ztxmao** [goproxyio/goproxy#55]
hi、When I am build goproxy in go1.12,I got this:
go generate
go build
> go: finding github.com/goproxyio/goproxy/internal/sys latest
> go: finding github.com/goproxyio/goproxy/internal latest
> build github.com/goproxyio/goproxy: cannot load github.com/goproxyio/goproxy/internal/sys: cannot find module providing package github.com/goproxyio/goproxy/internal/sys

**Comment by oiooj** [comment]
@ztxmao Plase use `go1.11` at this moment.

**Comment by edwardpro** [comment]
The same to this case. Also use go 1.12

**Comment by oiooj** [comment]
#61
