### ISSUE TITLE
【Unstable】It always failed to fetch some package

### ISSUE THREAD

**Issue by phper-chen** [goproxyio/goproxy#56]
￼￼￼
![image](https://user-images.githubusercontent.com/20152358/53615444-dd3aa300-3c18-11e9-90cc-a6af0cd1ed8c.png)

**Comment by oiooj** [comment]
The repo `github.com/anmitu/go-shlex` not exist anymore.

**Comment by oiooj** [comment]
I can not reproduce it:

```
Sosara@MBA:/tmp/test$ go get golang.org/x/perf
go: finding golang.org/x/perf latest
go: downloading golang.org/x/perf v0.0.0-20190124201629-844a5f5b46f4
go: extracting golang.org/x/perf v0.0.0-20190124201629-844a5f5b46f4

Sosara@MBA:/tmp/test$ go get github.com/anmitsu/go-shlex@latest
go: finding github.com/anmitsu/go-shlex latest
go: downloading github.com/anmitsu/go-shlex v0.0.0-20161002113705-648efa622239
go: extracting github.com/anmitsu/go-shlex v0.0.0-20161002113705-648efa622239
```

**Comment by phper-chen** [comment]
The cmd I had used was "go get -u google.golang.org/grpc"

**Comment by dreamlu** [comment]
when I use docker, it failed too,like this:
go: finding github.com/envoyproxy/go-control-plane/envoy/config/filter/network/tcp_proxy latest
go: finding golang.org/x/tools v0.0.0-20180221164845-07fd8470d635
go: golang.org/x/tools@v0.0.0-20180221164845-07fd8470d635: unexpected status (http://localhost:8081/golang.org/x/tools/@v/v0.0.0-20180221164845-07fd8470d635.info): 400 Bad Request
go: finding github.com/hashicorp/vic v1.5.1-0.20190403131502-bbfe86ec9443
go: error loading module requirements

**Comment by duramen** [comment]
go 1.11.4
go get failure
`D:\>go get -u -v go.etcd.io/etcd/clientv3
Fetching https://go.etcd.io/etcd/clientv3?go-get=1
https fetch failed: Get https://go.etcd.io/etcd/clientv3?go-get=1: proxyconnect tcp: dial tcp: lookup "https: no such host
package go.etcd.io/etcd/clientv3: unrecognized import path "go.etcd.io/etcd/clientv3" (https fetch: Get https://go.etcd.io/etcd/clientv3?go-get=1: proxyconnect tcp: dial tcp: lookup "https: no such host)`

**Comment by yougg** [comment]
It always failed to go get latest golang sdk version via goproxy.io

```bash
$export GO111MODULE=on GOPROXY=https://goproxy.io

$go get -v golang.org/dl/go1.12.5
Fetching https://goproxy.io/golang.org/dl/go1.12.5/@v/list
go: finding golang.org/dl/go1.12.5 latest
Fetching https://goproxy.io/golang.org/dl/go1.12.5/@latest
Fetching https://goproxy.io/golang.org/dl/@v/list
go: finding golang.org/dl latest
Fetching https://goproxy.io/golang.org/dl/@latest
Fetching https://goproxy.io/golang.org/dl/@v/v0.0.0-20190507014322-219d744c5398.mod
golang.org/dl/internal/version
golang.org/dl/go1.12.5

$go get -v golang.org/dl/go1.12.6
Fetching https://goproxy.io/golang.org/dl/go1.12.6/@v/list
go: finding golang.org/dl/go1.12.6 latest
Fetching https://goproxy.io/golang.org/dl/go1.12.6/@latest
Fetching https://goproxy.io/golang.org/dl/@v/list
go: finding golang.org/dl latest
Fetching https://goproxy.io/golang.org/dl/@latest
go: downloading golang.org/dl v0.0.0-20190507014322-219d744c5398
Fetching https://goproxy.io/golang.org/dl/@v/v0.0.0-20190507014322-219d744c5398.zip
go: extracting golang.org/dl v0.0.0-20190507014322-219d744c5398
Fetching https://goproxy.io/golang.org/@v/list
go: finding golang.org latest
Fetching https://goproxy.io/golang.org/@latest
Fetching https://goproxy.io/golang.org/@v/list
go get golang.org/dl/go1.12.6: no matching versions for query "latest"
```

**Comment by notedit** [comment]
```
Fetching https://golang.org/x/sys/unix?go-get=1
https fetch failed: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (https fetch: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```

same here.

**Comment by oiooj** [comment]
@notedit 

Seems that you are not using goproxy server, 
Pleasse run `export GOPROXY=https://goproxy.io` and try `go get golang.org/x/sys/unix`.

**Comment by notedit** [comment]
@oiooj  Sorry,  my fault.  It works now.

Do this project have a donate link?   It really helps.

**Comment by oiooj** [comment]
@notedit I'm very happy I can help you, we don't a have donate link yet. Just enjoy this service.

**Comment by abonec** [comment]
I have regular error like this:
```
go: finding stash.tutu.ru/mtp/pipeline v0.0.0-20190722103631-9c0e9aaa3a1f
go: finding github.com/Shopify/sarama v1.22.1
go: stash.tutu.ru/mtp/pipeline@v0.0.0-20190722103631-9c0e9aaa3a1f: unexpected status (http://goproxy.devel.tutu.ru/stash.tutu.ru/mtp/pipeline/@v/v0.0.0-20190722103631-9c0e9aaa3a1f.info): 400 Bad Request
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding github.com/prometheus/tsdb v0.7.1
```
It could be with a completely different package, private repo (like above), from github and so on. Seems that when goproxy first meet some error from repo hosting provider it cache error and always propagate this error to the users until goproxy restart. Restarting goproxy solve this problem for a while until the next error from repo hosting would be returned. Because of that we have to restart goproxy a few times a day.

**Comment by oiooj** [comment]
@abonec It's a known issue, we can fix it in this week, thanks for your report.
