### ISSUE TITLE
`go get -u` could not get latest minor or patch releases

### ISSUE THREAD

**Issue by fitzix** [goproxyio/goproxy#58]
`go get -u` unable to download the new version just released, is there a cache or a delay?
It works fine when I remove GOPROXY.

**Comment by fitzix** [comment]
But it works fine when i remove `GOPROXY`.

**Comment by oiooj** [comment]
@fitzix  Can you provide the `import path`?

**Comment by fitzix** [comment]
> @fitzix Can you provide the `import path`?

`github.com/fitzix/proxy-test` I have released several versions for testing, but it only downloads v0.0.1.

**Comment by oiooj** [comment]
fixed and deployed online:

```
# go get github.com/fitzix/proxy-test@latest
go: finding github.com/fitzix/proxy-test v0.0.3
go: downloading github.com/fitzix/proxy-test v0.0.3
```

**Comment by fitzix** [comment]
It works fine now

**Comment by oiooj** [comment]
Thanks for your feedback.
