### ISSUE TITLE
你好，我使用 set export GOPROXY=https://goproxy.io，仍然无法拉去依赖包

### ISSUE THREAD

**Issue by EddieChan1993** [goproxyio/goproxy#59]
> set export GOPROXY=https://goproxy.io
> go list
`
go: finding github.com/ugorji/go/codec latest
go: finding github.com/gin-contrib/sse latest
go: golang.org/x/sys@v0.0.0-20190222072716-a9d3bda3a223: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go: error loading module requirements
`

**Comment by oiooj** [comment]
1.  Make sure you enable module mode by `export GO111MODULE=on`
2. export GOPROXY=https://goproxy.io

@EddieChan1993 直接执行 `export GOPROXY=https://goproxy.io` 然后再试试。

**Comment by EddieChan1993** [comment]
thanks
