### ISSUE TITLE
can't get last tag version

### ISSUE THREAD

**Issue by kekekeke4** [goproxyio/goproxy#62]
1、i create a reposity A on my github,then  i push my all code to the reposity and create tag "v1.0.0" for the reposity
2、i create go project B and import the package from github reposity A   in my project B,that get the lastest version tag。
3、then i modify reposity A code and push to github,create tag v1.0.1 this time,to project B i run 
"go build" command that can't use the v1.0.1 code from reposity A even i modify the version in go.mod file,but i cancel the goproxy , that's ok

**Comment by kekekeke4** [comment]
i use the goproxy is https://goproxy.io

**Comment by oiooj** [comment]
@kekekeke4 Thanks for your report, I fixed and deployed, can you try it again?

**Comment by kekekeke4** [comment]
ok,i'll try again later and give you feedback

**Comment by kekekeke4** [comment]
i tried again,but that's not ok,the log is:
**go: finding github.com/kekekeke4/gomodtest v1.1.2
go: github.com/kekekeke4/gomodtest@v1.1.2: unexpected status (https://goproxy.io/github.com/kekekeke4/gomodtest/@v/v1.1.2.info): 500 Internal Server Error
go: error loading module requirements**

**Comment by kekekeke4** [comment]
this time , the log is 500 server error,  different from previous ones logs

**Comment by oiooj** [comment]
@kekekeke4 Thanks for your example, fixed at last.

**Comment by kekekeke4** [comment]
@oiooj tried again,It was already correct。
