### ISSUE TITLE
500 Internal Server Error when I execute go get gocloud.dev

### ISSUE THREAD

**Issue by fitzix** [goproxyio/goproxy#67]
> go get gocloud.dev: unexpected status (https://goproxy.io/gocloud.dev/@v/list): 500 Internal Server Error.

**Comment by fitzix** [comment]
I made a mistake, sorry.

**Comment by oiooj** [comment]
The server's DNS has some issue. Sorry about that. Now fixed, try it again. @fitzix Thanks for your report.
