### ISSUE TITLE
go get -u is not latest version ,is bug?

### ISSUE THREAD

**Issue by foolin** [goproxyio/goproxy#68]
I create a repository github.com/foolin/goview, I made a mistake the repository is empty first, and i use the command:
```
go get github.com/foolin/goview
```

Then, I push the code to github, but I can't update the new version for forever,  I clean the mod cache is sample problem:
```
go get -u github.com/foolin/goview
````
It always stay this version: 
```
github.com/foolin/goview v0.0.0-20190414112242-eef16598e03f
```

How can I get the latest new version?

**Comment by oiooj** [comment]
Oh, the server's DNS has some issue. Sorry about that. Now fixed, try it again.
