### ISSUE TITLE
cacheDir in docker-compose.yaml causes cache only in docker container.

### ISSUE THREAD

**Issue by rosbit** [goproxyio/goproxy#69]
if I attach the volume ./cacheDir to /ext as written in docker-compose.yaml, the logs show that goproxy will cache them under the path /go. So I edit docker-compose.yaml, change the line from "./cacheDir:/ext" to "./cacheDir:/go", goproxy write the files to the folder ./cacheDir.

**Comment by oiooj** [comment]
@rosbit Thanks for your report, can you pull a request for this?

**Comment by fancy-rabbit** [comment]
seems fix by #103

**Comment by oiooj** [comment]
Thanks
