### ISSUE TITLE
国内还是不能用啊，有没有官方 china 的 goproxy.io

### ISSUE THREAD

**Issue by lluck42** [goproxyio/goproxy#70]
国内还是不能用啊，有没有 china 的官方 goproxy.io 啊

**Comment by oiooj** [comment]
@lluck42 Which ISP you use?

![image](https://user-images.githubusercontent.com/2253095/56949761-4c277000-6b66-11e9-9473-8ebc883fb54d.png)

**Comment by lluck42** [comment]
@oiooj ISP is China Unicom 中国联通

没找到国内官方的，只有一个类似的 gopm 可以用
i can't find a resource of goproxy.io in china,
but find the project gopm althought it's not a offical package manager.

**Comment by gemark** [comment]
嗯... 感觉这个项目有些鸡肋。shadowsocket 后，墙又不是翻不了。翻的了，还要这个干啥呢？所以没明白这个项目的用途。

**Comment by gemark** [comment]
> @lluck42 Which ISP you use?
> 
> ![image](https://user-images.githubusercontent.com/2253095/56949761-4c277000-6b66-11e9-9473-8ebc883fb54d.png)
哥们不是我大天朝的吗？为何问句是洋文？are u russia? but u in china now

**Comment by oiooj** [comment]
Sorry about your confused.

**Comment by weixiao-huang** [comment]
@gemark 你可以用这个来架设自己的 goproxy 而不一定用 goproxy.io

**Comment by gemark** [comment]
> @gemark 你可以用这个来架设自己的 goproxy 而不一定用 goproxy.io

谢谢。我去试试。

**Comment by lluck42** [comment]
苦逼的是目前国内没有组织搭建 goproxy 这个项目

**Comment by snailchen** [comment]
> 嗯... 感觉这个项目有些鸡肋。shadowsocket 后，墙又不是翻不了。翻的了，还要这个干啥呢？所以没明白这个项目的用途。

团队开发的时候，这个当做私有仓库，类似于maven私有仓库，对于持续集成这种场景是非常有用的
