### ISSUE TITLE
为什么新建了releases但list里的版本没更新？

### ISSUE THREAD

**Issue by gojuukaze** [goproxyio/goproxy#72]
仓库之前没有创建releases，使用`https://goproxy.io/`代理拉了一次包，然后更新了代码创建了新的releases 
用`get get -u`，无法自动获取最新版本，list里也没有版本信息。只能手动指定版本。  
比如这个项目[https://goproxy.io/github.com/gojuukaze/go-watch-file/](https://goproxy.io/github.com/gojuukaze/go-watch-file/)

**Comment by oiooj** [comment]
Fixed, Thanks for your report.

```
$ export GO111MODULE=on
$ export GOPROXY=https://goproxy.io
$ go get -u github.com/gojuukaze/go-watch-file
go: downloading github.com/gojuukaze/go-watch-file v1.0.3
go: extracting github.com/gojuukaze/go-watch-file v1.0.3
```
