### ISSUE TITLE
Cannot parse capital package

### ISSUE THREAD

**Issue by weixiao-huang** [goproxyio/goproxy#73]
I try to use goproxy however I find it cannot parse packages whose name contain capital letters

```bash
> export GOPROXY=https://goproxy.io
> go get
go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
```

**Comment by oiooj** [comment]
@weixiao-huang The author of logrus defined `github.com/sirupsen/logrus
 ` as the repo's module name, so you should use `github.com/sirupsen/logrus
 `, not `github.com/Sirupsen/logrus`

see: https://github.com/sirupsen/logrus/blob/master/go.mod#L1
