### ISSUE TITLE
can i control the caching time ？

### ISSUE THREAD

**Issue by blacksun1977** [goproxyio/goproxy#74]
i setup a private goproxy, when i release a new git tag and use it immediately , the goproxy give an "goproxy: unknown revision v1.1.0" message, but after long time or restart the goproxy, it becomes ok, so i ask :
how long of the caching time to obtain git tag info？
where can i to adjust the caching time ?

**Comment by oiooj** [comment]
Could you help me to test this bug, I fixed it on master, feel free to reopen it.
Thanks @blacksun1977
