### ISSUE TITLE
Can't recognize newly added repo tags

### ISSUE THREAD

**Issue by ISukhanov** [goproxyio/goproxy#75]
I'm using local private goproxy with private repo (atlassian bitbucket)
repo A - comitted some code and added version tag v0.0.1
repo B - imported package from repo A and stated v0.0.1 in go.mod file
Added some code to repo A and tagged it with v0.0.2
changed go.mod file in repo B to follow version changes - changed to v0.0.2
GOPROXY can't get tag v0.0.2, console log:
2019/07/04 13:59:33 goproxy: 127.0.0.1:38454 request repoA/@v/v0.0.2.info
2019/07/04 13:59:33 goproxy: lookup repoA@v0.0.5 get err unknown revision v0.0.2
2019/07/04 13:59:33 goproxy: unknown revision v0.0.2

after restart of GOPROXY all working as expected:
2019/07/04 14:00:15 goproxy: 2019-07-04 14:00:15 inited. listen on 0.0.0.0:8081
2019/07/04 14:00:19 goproxy: 127.0.0.1:38474 request repoA/@v/v0.0.2.info
2019/07/04 14:00:19 goproxy: 127.0.0.1:38474 request repoA/@v/v0.0.2.mod
2019/07/04 14:00:19 goproxy: 127.0.0.1:38474 request repoA/@v/v0.0.2.zip

**Comment by oiooj** [comment]
@ISukhanov  Could you help me to test this bug, I fixed it on master, feel free to reopen it.
