### ISSUE TITLE
About pictures on the official website

### ISSUE THREAD

**Issue by GoneGo1ng** [goproxyio/goproxy#78]
Taiwan is an inseparable part of the People's Republic of China.
Please mark the colours of Taiwan and the mainland as the same.
![image](https://user-images.githubusercontent.com/35555900/60855179-4cfb1300-a235-11e9-9c45-7b192038ffd2.png)

**Comment by prologic** [comment]
I'm not sure the colors used are what you think they are.

> Who are using goproxy.io

it looks like from my perspective; there are more users using goproxy in Chine than any other part of the world. I take the darker shade meaning as "more users".

**Comment by GoneGo1ng** [comment]
@prologic 
Maybe I didn't express what I meant.
I know the darker shade meaning as "more users".
But I think you distinguish countries by colour.
So Taiwan and the mainland should not use different colours.

**Comment by prologic** [comment]
> @prologic
> Maybe I didn't express what I meant.
> I know the darker shade meaning as "more users".
> But I think you distinguish countries by colour.
> So Taiwan and the mainland should not use different colours.

I _think_ you've missed the point entirely.

It looks like the colours used here are different shades of blue.

The darker the shade of blue the more users.

This means currently that goproxy has more users in:

* America
* China

And only moderate users everywhere else and none in many parts of Africa (_as you'd expect at this stage of Global Internet usage_).

----

(_this should not even come up in OSS projects; but.._)

> I respect that you believe that Taiwan is part of China; and I don't question that. I only question your interpretation of the colours used in shading parts of the world map where users of goproxy are coming from likely based on their Source IP address and likely using a GeoIP database.

**Comment by GoneGo1ng** [comment]
@prologic 
Thank you for your explanation and respect.
Maybe I'm too sensitive to this problem.

**Comment by prologic** [comment]
Maybe... :) -- But we should left the authors of this project comment.

I could be entirely wrong! -- Was just sharing my perspective :)

**Comment by oiooj** [comment]
@GoneGo1ng 

Fixed, thanks for your report.
![image](https://user-images.githubusercontent.com/2253095/61102476-86838680-a4a0-11e9-8f1e-9bc766dde955.png)

Please refresh or restart your browser.
