### ISSUE TITLE
Some libraries will always have unexpected end of JSON input errors

### ISSUE THREAD

**Issue by fitzix** [goproxyio/goproxy#79]
Most of the vscode goalng extended dependencies will get this error, such as `github.com/mdempsky/gocode`, `golang.org/x/tools/cmd/guru`, `golang.org/x/tools/cmd/gopls`.

> go get -v golang.org/x/tools/cmd/gopls
go: finding golang.org/x/tools/cmd/gopls latest
go: finding golang.org/x/tools/cmd latest
go: finding golang.org latest
go: finding golang.org/x/tools latest
go: finding golang.org/x latest
go get golang.org/x/tools/cmd/gopls: module golang.org/x/tools/cmd: unexpected end of JSON input

**Comment by oiooj** [comment]
@fitzix  What's your `GOPROXY` env ? Which commit version you use if you build by yourself?

**Comment by fitzix** [comment]
> GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fitz/Library/Caches/go-build"
GOENV="/Users/fitz/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fitz/.go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6w/2ynsrj4d4fqd7vxrf1gmkq4w0000gn/T/go-build692195248=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by fitzix** [comment]
It is weird, remove GOPROXY and  use the default `GOPROXY="https://proxy.golang.org,direct"`, no error.

> go get -v golang.org/x/tools/cmd/gopls
get "golang.org/x/tools/cmd/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/cmd/gopls?go-get=1
get "golang.org/x/tools/cmd/gopls": verifying non-authoritative meta tag
go: finding golang.org/x/tools/cmd/gopls latest
go: finding golang.org/x/tools latest

**Comment by oiooj** [comment]
I can not reproduce you issue use goproxy.io , log:

```
Sosara@MBA:/tmp$ go get -v golang.org/x/tools/cmd/gopls
go: finding golang.org/x/tools/cmd/gopls latest
go: finding golang.org/x latest
go: finding golang.org latest
go: finding golang.org/x/tools/cmd latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190606050223-4d9ae51c2468
go: extracting golang.org/x/tools v0.0.0-20190606050223-4d9ae51c2468
go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: extracting golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58

```

**Comment by fitzix** [comment]
This problem will only appear on 1.13，may be caused by some bugs in 1.13beta1.

**Comment by oiooj** [comment]
Yes, I can reproduce with go1.13beta1

```
# go version
go version go1.13beta1 linux/amd64
# go get github.com/rocknio/micro-assets@latest -v
go: finding github.com/rocknio/micro-assets latest
go: finding github.com latest
go: finding github.com/rocknio latest
go get github.com/rocknio/micro-assets@latest: module github.com/rocknio/micro-assets: unexpected end of JSON input
```

**Comment by oiooj** [comment]
@fitzix I fixed this issue and deployed online, can you help me to confirm this bug is fixed?

**Comment by fitzix** [comment]
Sure, I tested the dependency of the vscode go plugin, it works fine now, thank u.
