### ISSUE TITLE
Use path.Match instead of regexp

### ISSUE THREAD

**Issue by oiooj** [goproxyio/goproxy#93]
The flag `exclude` in router mode should be  a comma-separated list of glob patterns (in the syntax of Go's path.Match) of module path prefixes.

For example,
	`*.corp.example.com,rsc.io/private`

---

Now, we use `regexp` in https://github.com/goproxyio/goproxy/blob/master/proxy/router.go#L47

We can use this func from Go:
https://github.com/golang/go/blob/82cf8bca9cf20297bc0edf481cc530c9b3f4bf1e/src/cmd/go/internal/str/path.go#L54-L96

and we need set a `GOPRIVATE ` maybe in router mode.

/cc @imneov @prologic

**Comment by imneov** [comment]
nice!
