### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by orestonce** [goproxyio/goproxy#98]
- docker build . -t goproxy
- docker run -d -p 8081:8081 goproxy
- Then I wrote a script to test :
````
#!/usr/bin/env bash

export GO111MODULE=on
export GOPROXY='http://127.0.0.1:8081'
export GOPATH=`pwd`

go get -v golang.org/x/crypto
````
- Script output: 

> go: finding golang.org/x/mod v0.1.0
Fetching http://127.0.0.1:8081/golang.org/x/mod/@v/v0.1.0.info
go: finding golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
Fetching http://127.0.0.1:8081/golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
go: golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4: unexpected status (http://127.0.0.1:8081/golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info): 404 Not Found
go: golang.org/x/mod@v0.1.0: unexpected status (http://127.0.0.1:8081/golang.org/x/mod/@v/v0.1.0.info): 404 Not Found
go: error loading module requirements
- docker logs output:
> docker logs 5eb9215b4acc
0.630s 404 /golang.org/x/mod/@v/v0.1.0.info
0.629s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.614s 404 /golang.org/x/mod/@v/v0.1.0.info
0.612s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.640s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.651s 404 /golang.org/x/mod/@v/v0.1.0.info
0.652s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.660s 404 /golang.org/x/mod/@v/v0.1.0.info

* When I replace `http://127.0.0.1:8081` to `https://goproxy.io` it is no problem.
````
 #!/usr/bin/env bash

export GO111MODULE=on
export GOPROXY='http://goproxy.io'
export GOPATH=`pwd`

go get -v golang.org/x/crypto
````
> `# go version`
> `go version go1.12.7 linux/amd64`

**Comment by oiooj** [comment]
@orestonce Can you access golang.org/x/* ?

Can you try this:

```
#!/usr/bin/env bash

export GO111MODULE=on
export GOPROXY='http://127.0.0.1:8081'
export GOPATH=`pwd`

go get -v github.com/gorilla/mux
```

**Comment by orestonce** [comment]
@oiooj  Yes . I can access golang.org/x/*
* I tried the above but the problem remains.
````
[root@localhost test]# cat get_test.sh 
#!/usr/bin/env bash

export GO111MODULE=on
export GOPROXY='http://127.0.0.1:8081'
export GOPATH=`pwd`

go get -v github.com/gorilla/mux
[root@localhost test]# sh get_test.sh 
go: finding golang.org/x/mod v0.1.0
Fetching http://127.0.0.1:8081/golang.org/x/mod/@v/v0.1.0.info
go: finding golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
Fetching http://127.0.0.1:8081/golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
go: golang.org/x/mod@v0.1.0: unexpected status (http://127.0.0.1:8081/golang.org/x/mod/@v/v0.1.0.info): 404 Not Found
go: golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4: unexpected status (http://127.0.0.1:8081/golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info): 404 Not Found
go: error loading module requirements
[root@localhost test]# docker logs 5eb9215b4acc
0.630s 404 /golang.org/x/mod/@v/v0.1.0.info
0.629s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.614s 404 /golang.org/x/mod/@v/v0.1.0.info
0.612s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.640s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.651s 404 /golang.org/x/mod/@v/v0.1.0.info
0.652s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.660s 404 /golang.org/x/mod/@v/v0.1.0.info
0.921s 404 /golang.org/x/mod/@v/v0.1.0.info
0.919s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.823s 404 /golang.org/x/mod/@v/v0.1.0.info
0.854s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.797s 404 /golang.org/x/mod/@v/v0.1.0.info
0.868s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.773s 404 /golang.org/x/mod/@v/v0.1.0.info
0.825s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.756s 404 /golang.org/x/mod/@v/v0.1.0.info
0.824s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
0.830s 404 /golang.org/x/mod/@v/v0.1.0.info
0.871s 404 /golang.org/x/crypto/@v/v0.0.0-20190701094942-4def268fd1a4.info
````

**Comment by imneov** [comment]
The 404 error will cause:
1. go version < 1.12 or GO111MODULE is not ON
2. run goproxy  not in a go modules director.

**Comment by imneov** [comment]
Maybe we can add same check on starting.   @oiooj

**Comment by oiooj** [comment]
@imneov Yes, We should.

**Comment by logrusorgru** [comment]
Hm, got the same. Currently, I'm using it with
```
GO111MODULE=on GOPROXY= goproxy -listen=127.0.0.1:8097
```
And, seems, it works.

**Comment by dlhf** [comment]
dubbo-go can't download

**Comment by oiooj** [comment]
> dubbo-go can't download

```
GO111MODULE="on"
GOPROXY="https://goproxy.io,direct"
```

```
$ cd /tmp
$ go get -v github.com/apache/dubbo-go
go: downloading github.com/apache/dubbo-go v1.2.0
go: finding versions for github.com/apache
go: github.com/apache/dubbo-go upgrade => v1.2.0
```

```
ll ~/golang/pkg/mod/cache/download/github.com/apache/dubbo-go/\@v/
total 760
drwxr-xr-x  9 libk  staff     288 Nov 22 10:00 .
drwxr-xr-x  3 libk  staff      96 Nov 22 10:00 ..
-rw-r--r--  1 libk  staff       7 Nov 22 10:00 list
-rw-r--r--  1 libk  staff       0 Nov 22 10:00 list.lock
-rw-r--r--  1 libk  staff      50 Nov 22 10:00 v1.2.0.info
-rw-r--r--  1 libk  staff       0 Nov 22 10:00 v1.2.0.lock
-rw-r--r--  1 libk  staff    2754 Nov 22 10:00 v1.2.0.mod
-rw-------  1 libk  staff  372114 Nov 22 10:00 v1.2.0.zip
-rw-r--r--  1 libk  staff      47 Nov 22 10:00 v1.2.0.ziphash
```

@dlhf Can you send me more detail? What's your `go env` log? And your error log of `go get -v github.com/apache/dubbo-go` .

**Comment by dlhf** [comment]
only set GOPROXY="https://goproxy.io"

**Comment by navono** [comment]
got the same.

```
$go version
go version go1.13.7 windows/amd64

$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\pingqixing\AppData\Local\go-build
set GOENV=C:\Users\pingqixing\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Go
set GOPRIVATE=
set GOPROXY=http://10.10.21.34:10080
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\sourcecode\go\demo\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\PINGQI~1\AppD
ata\Local\Temp\go-build250203034=/tmp/go-build -gno-record-gcc-switches
```

> go get github.com/urfave/cli/v2

![goproxy](https://user-images.githubusercontent.com/3746639/74312100-f39b2980-4dab-11ea-8a27-20d432da2da9.PNG)

**Comment by navono** [comment]
Build binary with 
```
GO111MODULE=on GOPROXY= 
```
in Win10, then run it, it works.

**Comment by navono** [comment]
About the sumDB error, just set `GOSUBDB` to `off`.

**Comment by oiooj** [comment]
@navono Thanks your feedback, and #134 fixed this issue.

**Comment by fcddk** [comment]
go.mod:12: require github.com/prometheus/prometheus: reading https://goproxy.io/github.com/prometheus/prometheus/@v/v2.25.0.info: 404 Not Found
	server response: not found: github.com/prometheus/prometheus@v2.25.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

**Comment by fcddk** [comment]
How to solve this problem?

**Comment by oiooj** [comment]
@fcddk The `github.com/prometheus/prometheus` import path should be upgrade to v2, and then we can use ``github.com/prometheus/prometheus/v2` as our import path in our program.

`github.com/prometheus/prometheus` used by v0 and v1, so it can not found v2 tags.

**Comment by EldarKurbanov** [comment]
Flag `-proxy https://goproxy.io` or `-proxy https://proxy.golang.org` works for me

**Comment by AdityaHitachi** [comment]
Facing 404 error while running go build cmd with GOPROXY.
